apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflask-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appflask
  template:
    metadata:
      labels:
        app: appflask # mesmo do matchLabels acima
    spec:
      containers:
      - name: appflask
        image: ronafreitasweb/webapiflask:tagversion
        #image: ronafreitasweb/webapiflask:latest
        ports:
          - containerPort: 5000

---

# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: appflask-service
spec:
  type: LoadBalancer # NodePort - LoadBalancer
  selector:
    app: appflask # template:  metadata:  labels:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # explicação no video em 02:29:00
      #nodePort: 30000 # explicação a partir de 01:51:00
