apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapiflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapiflask
  template:
    metadata:
      labels:
        app: webapiflask # mesmo do matchLabels acima
    spec:
      containers:
      - name: webapiflask
        #image: ronafreitasweb/webapiflask:v1
        image: ronafreitasweb/webapiflask:{{tagversion}}
        ports:
          - containerPort: 5000

---

# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: webapiflask
spec:
  type: LoadBalancer # NodePort - LoadBalancer
  selector:
    app: webapiflask # template:  metadata:  labels:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # explicação no video em 02:29:00
      #nodePort: 30000 # explicação a partir de 01:51:00
