apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appflask
  template:
    metadata:
      labels:
        app: appflask # mesmo do matchLabels acima
    spec:
      containers:
      - name: appflask
        #image: ronafreitasweb/webapiflask:v1
        image: ronafreitasweb/webapiflask:v{{tag}}
        ports:
          - containerPort: 5000

---

# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: appflask
spec:
  selector:
    app: appflask # template:  metadata:  labels:
  ports:
  - port: 80
    targetPort: 5000 # explicação no video em 02:29:00
    nodePort: 30000 # explicação a partir de 01:51:00
  type: LoadBalancer # NodePort - LoadBalancer
